version: "3.9"

services:
  andrea:
    build: .
    image: andrea:latest
    container_name: andrea
    network_mode: host
    pull_policy: never

networks:
  default: 
    external: true
    name: host